### ISSUE TITLE
Reports fs.exists() to be blocking with Node V8.x

### ISSUE THREAD

**Issue by gjegadesh** [naugtur/blocked-at#17]
I am surprised to see that fs.exists() blocks. Please clarify. Thanks

[2018/07/03 11:25:45.933] [INFO] { blockedFor: 1054.224799987793,
  stack: 
   [ '    at Object.fs.exists (fs.js:310:11)',
     '    at getXYZ (C:\\dev\\prj1\\routes\\XYZ.js:122:10)',
     '    at h.XYZ (C:\\dev\\prj1\\routes\\XYZ.js:69:37)',
     '    at Layer.handle [as handle_request] (C:\\dev\\prj1\\node_modules\\express\\lib\\router\\layer.js:95:5)',
     '    at trim_prefix (C:\\dev\\prj1\\node_modules\\express\\lib\\router\\index.js:312:13)',
     '    at C:\\dev\\prj1\\node_modules\\express\\lib\\router\\index.js:280:7',
     '    at Function.process_params (C:\\dev\\prj1\\node_modules\\express\\lib\\router\\index.js:330:12)',
     '    at next (C:\\dev\\prj1\\node_modules\\express\\lib\\router\\index.js:271:10)',
     '    at SendStream.error (C:\\dev\\prj1\\node_modules\\serve-static\\index.js:121:7)',
     '    at emitOne (events.js:116:13)',
     '    at SendStream.emit (events.js:211:7)',
     '    at SendStream.error (C:\\dev\\prj1\\node_modules\\send\\index.js:275:17)',
     '    at SendStream.onStatError (C:\\dev\\prj1\\node_modules\\send\\index.js:392:12)',
     '    at onstat (C:\\dev\\prj1\\node_modules\\send\\index.js:674:26)',
     '    at FSReqWrap.oncomplete (fs.js:152:21)' ] }

**Comment by naugtur** [comment]
It doesn't block, so this is a false positive. 
Would you be so kind to try and add a PR with a testcase for this?

**Comment by yyfearth** [comment]
I think it has false positive on async and await.
