### ISSUE TITLE
Import triggers false positive

### ISSUE THREAD

**Issue by LJNeon** [naugtur/blocked-at#31]
Whenever I start the process, it triggers hundreds of errors, all nearly identical to the following:
```
7/12/2020, 12:49:30 AM [WARN] Blocked (51.30170703125ms) [
  '    at link (internal/modules/esm/module_job.js:42:32)',
  '    at new ModuleJob (internal/modules/esm/module_job.js:63:19)',
  '    at Loader.getModuleJob (internal/modules/esm/loader.js:242:11)'
]
```

**Comment by naugtur** [comment]
Very interesting. Could you share a setup/example for me too instantly reproduce?
Node version and any other context appreciated.

**Comment by LJNeon** [comment]
I spent maybe 30 minutes trying to create a bare-bones repro and was entirely unable to. I don't have time to look into it in more detail, and this is for a project that isn't open-source so I can't share the source. Node version was the latest version of v14 at the time. It's a fairly big project with many files, if that's useful context.
