### ISSUE TITLE
getting OOM errors since using this

### ISSUE THREAD

**Issue by contra** [naugtur/blocked-at#7]
```
Blocked for 2928.1773420104983ms:
    at Function.runHooks (~/Projects/staeco/node_modules/sequelize/lib/hooks.js:116:20)
    at InstanceValidator._validateAndRunHooks (~/Projects/staeco/node_modules/sequelize/lib/instance-validator.js:108:12)
    at InstanceValidator.validate (~/Projects/staeco/node_modules/sequelize/lib/instance-validator.js:93:38)
    at model.validate (~/Projects/staeco/node_modules/sequelize/lib/model.js:3733:49)
    at Promise.try (~/Projects/staeco/node_modules/sequelize/lib/model.js:3510:21)
    at model.save (~/Projects/staeco/node_modules/sequelize/lib/model.js:3507:23)
    at model.update (~/Projects/staeco/node_modules/sequelize/lib/model.js:3767:17)
    at ~/Projects/staeco/server/endpoints/importer/job/updateById.js:34:14
    at Generator.next (<anonymous>)
    at step (~/Projects/staeco/server/endpoints/importer/job/updateById.js:16:191)
    at ~/Projects/staeco/server/endpoints/importer/job/updateById.js:16:361
    at <anonymous>

<--- Last few GCs --->

[729:0x102802200]  2320969 ms: Mark-sweep 1518.7 (2703.1) -> 1518.0 (2703.1) MB, 386.3 / 0.0 ms  allocation failure GC in old space requested
[729:0x102802200]  2321334 ms: Mark-sweep 1518.0 (2703.1) -> 1517.9 (2657.1) MB, 364.9 / 0.0 ms  last resort
[729:0x102802200]  2321698 ms: Mark-sweep 1517.9 (2657.1) -> 1517.9 (2652.1) MB, 364.2 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x11b70a71cef1 <JSObject>
    0: builtin exit frame: Function(aka Function)(this=0x11b70a702241 <undefined>,0xc57a3ffd2b1 <Very long string[3348]>,0x34426c74e3f1 <String[7]: rowData>,0x2ec7a023ad39 <String[7]: parsers>)

    2: addFields [/Users/contra/Projects/staeco/node_modules/pg/lib/result.js:110] [bytecode=0x383cc25ff129 offset=180](this=0x3e19048f5ee1 <Result map = 0x3932693dff81>,fieldDescriptions=0x37c73025c619 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 5: v8::internal::HashTable<v8::internal::StringTable, v8::internal::StringTableShape, v8::internal::HashTableKey*>::EnsureCapacity(v8::internal::Handle<v8::internal::StringTable>, int, v8::internal::HashTableKey*, v8::internal::PretenureFlag) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 6: v8::internal::StringTable::LookupKey(v8::internal::Isolate*, v8::internal::HashTableKey*) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 7: v8::internal::AstValueFactory::Internalize(v8::internal::Isolate*) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 8: v8::internal::parsing::ParseProgram(v8::internal::ParseInfo*, v8::internal::Isolate*, bool) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
 9: v8::internal::(anonymous namespace)::CompileToplevel(v8::internal::CompilationInfo*) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
10: v8::internal::Compiler::GetFunctionFromEval(v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::LanguageMode, v8::internal::ParseRestriction, int, int, int, int, int, v8::internal::Handle<v8::internal::Object>, v8::ScriptOriginOptions) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
11: v8::internal::Compiler::GetFunctionFromString(v8::internal::Handle<v8::internal::Context>, v8::internal::Handle<v8::internal::String>, v8::internal::ParseRestriction, int) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
12: v8::internal::(anonymous namespace)::CreateDynamicFunction(v8::internal::Isolate*, v8::internal::BuiltinArguments, char const*) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
13: v8::internal::Builtin_FunctionConstructor(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/contra/.nvm/versions/node/v8.4.0/bin/node]
14: 0x14d94aabc8dd
```

commenting out the code gets rid of the issue, so i'm 100% sure its coming from blocked-at.

code:

```js
import blocked from 'blocked-at'
import cleanStack from 'clean-stack'
import createLogger from 'lib/log'

// debug event loop blocks
const debug = createLogger({ name: 'server:event-loop' })

if (process.env.NODE_ENV === 'development') {
  blocked((time, stack) => {
    if (time < 500) return

    // filter out worthless bluebird stuff
    const filtered = stack.filter((msg) => msg.indexOf('node_modules/bluebird') === -1)
    if (filtered.length === 0) return
    
    // filter out more worthless crap
    const nstack = cleanStack(filtered.join('\n'), { pretty: true })
    if (nstack.length === 0) return

    const msg = `Blocked for ${time}ms:\n${nstack}`
    if (time > 10000) return debug.error(msg)
    if (time > 1000) return debug.warn(msg)
    debug(msg)
  })
}
```

**Comment by naugtur** [comment]
Thanks for reporting!
Is the snipped all the code required to reproduce? 
blocked-at could behave like leaking memory if you use a lot of recursion. I'm not aware of other cases.
If you can share a case that reproduces, I can introduce a capped collection, so instead of OOM you'd loose a report in a worst case scenario.

**Comment by contra** [comment]
Ah, I'll bet you its this: https://github.com/naugtur/blocked-at/blob/master/index.js#L19

Move this line to before the stack is constructed, and reset the value after? That way any stacks produced elsewhere aren't affected. I think it could be this library + newrelic producing stacks elsewhere causing the OOM. Or maybe just the infinite stack here and nothing else. Seems to happen when there are lots of blocked events happening quickly, so it could just be a ton of these massive Error stacks.

**Comment by contra** [comment]
Here's a better stack dump that shows the issue coming from https://github.com/naugtur/blocked-at/blob/master/index.js#L27

```
--- Last few GCs --->

[67497:0x102802200]  2012327 ms: Mark-sweep 1404.0 (2110.5) -> 1404.0 (2107.5) MB, 354.4 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 400 ms) last resort GC in old space requested
[67497:0x102802200]  2012680 ms: Mark-sweep 1404.0 (2107.5) -> 1404.0 (2107.5) MB, 353.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x14e3b7da5ec1 <JSObject>
    0: builtin exit frame: captureStackTrace(this=0x14e3b7d8d701 <JSFunction Error (sfi = 0x14e3d0d34f69)>,0x14e3fccfc549 <Object map = 0x14e39b7023b9>)

    1: emitInitNative [async_hooks.js:~466] [pc=0x37ed571c246](this=0x14e3fccfc519 <PromiseWrap map = 0x14e3b0a7dae9>,asyncId=483489,type=0x14e3b7da8c09 <String[7]: PROMISE>,triggerAsyncId=9,resource=0x14e3fccfc519 <PromiseWrap map = 0x14e3b0a7...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 4: v8::internal::Factory::NewTransitionArray(int) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 5: v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 6: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Handle<v8::internal::LayoutDescriptor>, v8::internal::TransitionFlag, v8::internal::MaybeHandle<v8::internal::Name>, char const*, v8::internal::SimpleTransitionFlag) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 7: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 8: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
 9: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Object::StoreFromKeyed) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
10: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
11: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
12: v8::internal::Object::SetProperty(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
13: v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
14: v8::internal::Builtin_Impl_ErrorCaptureStackTrace(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/contra/.nvm/versions/node/v8.9.0/bin/node]
15: 0x37ed540441d
```

**Comment by naugtur** [comment]
fixed by #8

**Comment by edbrannin** [comment]
FWIW, I've started seeing OOM Errors with this in my logs:

```
1: 0x19fc08a5d0d1 <Symbol: init>(aka init) [0x2866bed02559] [/usr/src/app/node_modules/blocked-at/index.js:~29] [pc=0x1860ecf4623d](this=0x2866bed02599 <AsyncHook map = 0x1c7033bbb931>,asyncId=252321,type=0x19fc08a22b61 <String[7]: PROMISE>,triggerAsyncId=114480,resource=0x330575134cc1 <PromiseWrap map = 0x3a3aa88717a9>)
--
```

(This is on version 1.2.0)

**Comment by naugtur** [comment]
What options are you passing?
If you have a whole lot of async contexts created suddenly it could be a normal behavior of async hooks, but there still could be a way out.

Share some more info about how long it takes for this to happen, what's the memory limit and memory footprint without it - if you know that. 

And for now only detect loop blocks with simpler techniques in production and go back to blocked-at when there's a blockage that's significant and not obvious to find.

I might be able to help when you share more info
